# Generated by Django 5.1.1 on 2024-09-24 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_remove_person_birth_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='industry',
        ),
        migrations.AlterField(
            model_name='company',
            name='linkedin_url',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='linkedin_url',
            field=models.URLField(null=True),
        ),
    ]
