# Generated by Django 5.1.1 on 2024-09-24 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_remove_company_industry_alter_company_linkedin_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
