# Generated by Django 5.1.1 on 2024-09-24 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_person_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='network',
            name='credits',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
