# Generated by Django 5.1.1 on 2024-09-24 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_network_credits'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Group',
        ),
    ]
