# Generated by Django 5.1.1 on 2024-09-24 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_delete_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='linkedin_identifier',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
