# Generated by Django 5.1.1 on 2024-09-24 21:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0007_alter_person_linkedin_identifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationexperience',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education_experiences', to='network.person'),
        ),
        migrations.AlterField(
            model_name='educationexperience',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education_experiences', to='network.school'),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_experiences', to='network.company'),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_experiences', to='network.person'),
        ),
    ]
