# Generated by Django 5.1.1 on 2024-09-26 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0008_alter_educationexperience_person_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='network',
            name='name',
            field=models.CharField(max_length=127, null=True),
        ),
    ]
