# Generated by Django 5.1.1 on 2024-09-26 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0009_network_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
