# Generated by Django 5.1.1 on 2024-09-26 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0010_person_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='image',
        ),
    ]
