# Generated by Django 5.1.1 on 2024-09-27 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0011_remove_person_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='network',
            name='companies',
        ),
        migrations.RemoveField(
            model_name='network',
            name='schools',
        ),
    ]
