version: '3.8'

services:
  proxycurl_mock:
    build:
      context: ./proxycurl_mock
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./proxycurl_mock/data:/app/data
