version: '3.8'

services:
  proxycurl_mock:
    build:
      context: ./proxycurl_mock
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./proxycurl_mock/data:/app/data

  smtp4dev:
    image: rnwood/smtp4dev
    ports:
      - "2500:2500"
      - "25:25"
      - "8888:80"
    restart: always
